const menuList = [
    {
        title:'首页',
        key:'/admin/home'
    },
    {
        title:'UI',
        key:'/admin/ui',
        children:[
            {
                title:'button组件',
                key:'/admin/ui/buttons',
            },
            {
                title:'modal组件',
                key:'/admin/ui/modals',
            },
            {
                title:'loading组件',
                key:'/admin/ui/loads',
            },
            {
                title:'notice组件',
                key:'/admin/ui/notices',
            },
            {
                title:'massage组件',
                key:'/admin/ui/massages',
            },
            {
                title:'Tab组件',
                key:'/admin/ui/tabs',
            },
            {
                title:'Gallery组件',
                key:'/admin/ui/gallerys',
            },
            {
                title:'Carousel组件',
                key:'/admin/ui/carousels',
            }
        ]
    },
    {
        title:'书籍',
        key:'/admin/books',
        children:[
            {
                title:'古诗文',
                key:'/admin/books/gsw',
            },
            {
                title:'小说',
                key:'/admin/books/xs',
            }
        ]
    },
    {
        title:'电影',
        key:'/admin/movies',
        children:[
            {
                title:'中国',
                key:'/admin/movies/ch',
            },
            {
                title:'欧美',
                key:'/admin/movies/us',
            },
            {
                title:'日韩',
                key:'/admin/movies/rh',
            },
        ]
    }
];
export default menuList;