const dataSource = [
    {
        id: 1,
        name: '测试1',
        sex: 0,
        state: 1,
        hobby: [0,2],
        birthday: '1997-02-19',
        city: ['guizhou','guiyang','huaxi'],
        address: '花溪大学城',
    },
    {
        id: 2,
        name: '测试2',
        sex: 0,
        state: 1,
        hobby: [0,2],
        birthday: '1997-02-19',
        city: ['guizhou','guiyang','huaxi'],
        address: '花溪大学城',
    },
    {
        id: 3,
        name: '测试3',
        sex: 0,
        state: 1,
        hobby: [0,2],
        birthday: '1997-02-19',
        city: ['guizhou','guiyang','huaxi'],
        address: '花溪大学城',
    },
    {
        id: 4,
        name: '测试4',
        sex: 0,
        state: 1,
        hobby: [0,2],
        birthday: '1997-02-19',
        city: ['guizhou','guiyang','huaxi'],
        address: '花溪大学城',
    },
    {
        id: 5,
        name: '测试5',
        sex: 0,
        state: 1,
        hobby: [0,2],
        birthday: '1997-02-19',
        city: ['guizhou','guiyang','huaxi'],
        address: '花溪大学城',
    },
    {
        id: 6,
        name: '测试6',
        sex: 0,
        state: 1,
        hobby: [0,2],
        birthday: '1997-02-19',
        city: ['guizhou','guiyang','huaxi'],
        address: '花溪大学城',
    },
    {
        id: 7,
        name: '测试7',
        sex: 0,
        state: 1,
        hobby: [0,2],
        birthday: '1997-02-19',
        city: ['guizhou','guiyang','huaxi'],
        address: '花溪大学城',
    },
    {
        id: 8,
        name: '测试8',
        sex: 0,
        state: 1,
        hobby: [0,2],
        birthday: '1997-02-19',
        city: ['guizhou','guiyang','huaxi'],
        address: '花溪大学城',
    },
    {
        id: 9,
        name: '测试9',
        sex: 0,
        state: 1,
        hobby: [0,2],
        birthday: '1997-02-19',
        city: ['guizhou','guiyang','huaxi'],
        address: '花溪大学城',
    },
    {
        id: 10,
        name: '测试10',
        sex: 0,
        state: 1,
        hobby: [0,2],
        birthday: '1997-02-19',
        city: ['guizhou','guiyang','huaxi'],
        address: '花溪大学城',
    },
    {
        id: 11,
        name: '测试11',
        sex: 0,
        state: 1,
        hobby: [0,2],
        birthday: '1997-02-19',
        city: ['guizhou','guiyang','huaxi'],
        address: '花溪大学城',
    }
];

export default dataSource;